version: '3.3'
services:
  db:
    container_name: mongodb
    image: 'mongo'        
    environment:
      - MONGO_INITDB_DATABASE=bidenergy
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=181173
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '27017-27019:27017-27019'    
    volumes:
      #- my-db:/mnt/d/database/mysql80
      #- /mnt/d/docker/compose-mysql/my.cnf:/etc/my.cnf
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

      #- /mnt/d/database/mysql80:/var/lib/mysql
# Names our volume
#volumes:
#  my-db: